import turtle as trl


def arc(angle, speed):
    trl.speed(10)
    for i in range(angle):
        trl.forward(speed)
        trl.right(1)


trl.shape('turtle')
trl.penup()
trl.goto(-200, 0)
trl.pendown()
trl.left(90)
trl.color('yellow')
trl.begin_fill()
arc(360, 4)
trl.end_fill()
trl.color('blue')
trl.penup()
trl.goto(-100, 100)
trl.pendown()
trl.begin_fill()
arc(360, 0.5)
trl.end_fill()
trl.penup()
trl.goto(70, 100)
trl.pendown()
trl.begin_fill()
arc(360, 0.5)
trl.end_fill()
trl.penup()
trl.goto(30, 85)
trl.right(180)
trl.pendown()
trl.width(15)
trl.color('black')
trl.forward(60)
trl.penup()
trl.goto(150, -60)
trl.pendown()
trl.color('red')
arc(180, 2)
trl.done()
