import turtle as trl
import numpy as np


def letter(n):
    if n == 1:
        trl.pendown()
        trl.left(45)
        trl.forward(np.sqrt(2)*20)
        trl.right(135)
        trl.forward(40)
        trl.backward(20)
        trl.left(90)
        trl.penup()
        trl.forward(10)
    if n == 0:
        trl.pendown()
        trl.right(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(40)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.penup()
        trl.forward(30)
    if n == 2:
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.pendown()
        trl.forward(20)
        trl.right(90)
        trl.forward(20)
        trl.right(45)
        trl.forward(np.sqrt(2)*20)
        trl.left(135)
        trl.forward(20)
        trl.penup()
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.forward(10)
    if n == 3:
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.pendown()
        trl.forward(20)
        trl.right(135)
        trl.forward(np.sqrt(2)*20)
        trl.left(135)
        trl.forward(20)
        trl.right(135)
        trl.forward(np.sqrt(2) * 20)
        trl.backward(np.sqrt(2) * 20)
        trl.left(135)
        trl.penup()
        trl.forward(10)
    if n == 4:
        trl.pendown()
        trl.left(90)
        trl.forward(20)
        trl.backward(20)
        trl.right(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.backward(40)
        trl.forward(20)
        trl.right(90)
        trl.penup()
        trl.forward(10)
    if n == 5:
        trl.pendown()
        trl.forward(20)
        trl.left(90)
        trl.penup()
        trl.forward(20)
        trl.pendown()
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.penup()
        trl.forward(20)
        trl.pendown()
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.penup()
        trl.forward(10)
    if n == 6:
        trl.pendown()
        trl.forward(20)
        trl.right(90)
        trl.forward(20)
        trl.right(90)
        trl.forward(20)
        trl.right(90)
        trl.forward(20)
        trl.right(45)
        trl.forward(np.sqrt(2)*20)
        trl.right(135)
        trl.penup()
        trl.forward(20)
        trl.left(90)
        trl.forward(10)
    if n == 7:
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.pendown()
        trl.forward(20)
        trl.right(135)
        trl.forward(20*np.sqrt(2))
        trl.left(45)
        trl.forward(20)
        trl.penup()
        trl.left(135)
        trl.forward(np.sqrt(2)*20)
        trl.right(45)
        trl.forward(10)
    if n == 8:
        trl.pendown()
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(40)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.right(90)
        trl.penup()
        trl.forward(10)
    if n == 9:
        trl.pendown()
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.left(90)
        trl.forward(20)
        trl.penup()
        trl.forward(20)
        trl.pendown()
        trl.left(135)
        trl.forward(np.sqrt(2) * 20)
        trl.right(45)
        trl.penup()
        trl.forward(10)


trl.color('cyan')
trl.shape('turtle')
trl.width(4)
number = input()
trl.penup()
trl.goto(-180, 0)
for m in number:
    letter(int(m))
trl.done()
